
server:
  port: 8788

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChwingWong/gs-microservice-config

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://admin:${app.registry.password}@${eureka.instance.hostname}:8761/eureka/

