
server:
  port: 18765

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:${app.registry.password}@${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true